version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '8000:80'
    volumes:
      - ${WWW}:/var/www/html/:cached
      - ../nginx/conf.d:/etc/nginx/conf.d/:cached
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ../log/nginx:/var/log/nginx:cached
    environment:
      - TZ=Asia/Shanghai
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ../mysql/conf/my.cnf:/etc/mysql/my.cnf:cached
      - ../log/mysql:/var/log/mysql:cached
    #restart: unless-stopped
    #tty: true
    ports:
      - '33006:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  redis:
    image: redis:latest
    ports:
      - '63790:6379'
    networks:
      - laravel

  php74:
    build:
      context: ../php/php74/
    container_name: php74
    volumes:
      - ${www}:/var/www/html/:cached
    expose:
      - 9000
    links:
      - redis:redis
    networks:
      - laravel
